import sys
import os.path
import datetime

from Cheetah.Template import Template

if len(sys.argv) != 3:
    print "Usage: %s <input> <output>" % sys.argv[0]
    sys.exit(0)

tmpl = Template(open(sys.argv[1], 'rt').read(), searchList=[])

out = open(sys.argv[2], 'wt');
out.write("""/*
This file is generated by expandTemplate.py
Do not modify.
Any changes made to this file will be lost.
Modify %s instead.
Last modification time: %s
*/

""" % (os.path.split(sys.argv[1])[1], datetime.datetime.now()));
out.write(str(tmpl))
